@endporint = http://127.0.0.1:3000
@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ODYxOTQzLWUzMzAtNDVkYy04YTcyLTg0OWVhYTVjZGEyOCIsImVtYWlsIjoiYXBpcmF0MTQxMjFpY2VAaG90bWFpbC5jb20iLCJmdWxsX25hbWUiOiJBcGlyYXQgUHJlbWFjaGFuYSIsInBob25lIjoiMDkyMjU2NzI4NyIsInBvc2l0aW9uIjoiYmFja2VuZCBkZXZlbG9wZXIyIiwiYmlvIjoiLSIsInByb2ZpbGVfcGF0aCI6IiIsImlhdCI6MTYzOTk0MTMwOCwiZXhwIjoxNjM5OTQxMzY4fQ.jA9P5Iu-hYFKx-E1KwL8NHtRuxTmk9IvnGSlWuqZx_g
### Login
POST {{endporint}}/auth/login
Content-Type: application/json

{
    "email":"apirat14121ice@hotmail.com",
    "password":"12345"
}


### Get Profile by token
GET {{endporint}}/profile
Content-Type: application/json
Authorization: Bearer {{access_token}}